UPDATE products SET image_url = '/src/assets/products/pista-kunafa.jpg' WHERE name = 'Pista Kunafa';
UPDATE products SET image_url = '/src/assets/products/biscoff-kunafa.jpg' WHERE name = 'Biscoff Kunafa';
UPDATE products SET image_url = '/src/assets/products/dark-chocolate.jpg' WHERE name = 'Plain Dark Chocolate';
UPDATE products SET image_url = '/src/assets/products/milk-chocolate.jpg' WHERE name = 'Milk Chocolate';
UPDATE products SET image_url = '/src/assets/products/white-chocolate.jpg' WHERE name = 'White Chocolate';
UPDATE products SET image_url = '/src/assets/products/marvel-double.jpg' WHERE name = 'Marvel Double';
UPDATE products SET image_url = '/src/assets/products/dark-milk-blend.jpg' WHERE name = 'Dark + Milk Blend';
UPDATE products SET image_url = '/src/assets/products/milk-white-blend.jpg' WHERE name = 'Milk + White Blend';
UPDATE products SET image_url = '/src/assets/products/white-dark-blend.jpg' WHERE name = 'White + Dark Blend';
UPDATE products SET image_url = '/src/assets/products/bubbly-chocolate.jpg' WHERE name = 'Bubbly Chocolate';
UPDATE products SET image_url = '/src/assets/products/bounty-bar.jpg' WHERE name = 'Bounty Bar';
UPDATE products SET image_url = '/src/assets/products/pan-chocolate.jpg' WHERE name = 'Pan Chocolate';
UPDATE products SET image_url = '/src/assets/products/crazy-crunch.jpg' WHERE name = 'Crazy Crunch';
UPDATE products SET image_url = '/src/assets/products/cornflakes-rocks.jpg' WHERE name = 'Cornflakes Rocks';
UPDATE products SET image_url = '/src/assets/products/nutty-rock.jpg' WHERE name = 'Chocolate Nutty Rock';
UPDATE products SET image_url = '/src/assets/products/truffle-chocolate.jpg' WHERE name = 'Truffle Chocolate';
UPDATE products SET image_url = '/src/assets/products/ferrero-bar.jpg' WHERE name = 'Ferrero Rocher Bar';
UPDATE products SET image_url = '/src/assets/products/coated-nuts.jpg' WHERE name = 'Coated Nuts';
UPDATE products SET image_url = '/src/assets/products/almond-bar.jpg' WHERE name = 'Roasted Almond Bar';
UPDATE products SET image_url = '/src/assets/products/cashew-crunch.jpg' WHERE name = 'Cashew Crunch';
UPDATE products SET image_url = '/src/assets/products/hazelnut-bar.jpg' WHERE name = 'Hazelnut Bar';
UPDATE products SET image_url = '/src/assets/products/butterscotch-bar.jpg' WHERE name = 'Butterscotch Bar';
UPDATE products SET image_url = '/src/assets/products/exotic-bites.jpg' WHERE name = 'Exotic Chocolate Bites';
UPDATE products SET image_url = '/src/assets/products/nutty-temptation.jpg' WHERE name = 'Nutty Temptation';
UPDATE products SET image_url = '/src/assets/products/oreo-crunch.jpg' WHERE name = 'Oreo Crunch';
UPDATE products SET image_url = '/src/assets/products/mixed-dryfruit.jpg' WHERE name = 'Mixed Dryfruit';
UPDATE products SET image_url = '/src/assets/products/jelly-centered.jpg' WHERE name = 'Soft Jelly Centered';
UPDATE products SET image_url = '/src/assets/products/wafer-bar.jpg' WHERE name = 'Wafer Chocolate Bar';
UPDATE products SET image_url = '/src/assets/products/choco-pop.jpg' WHERE name = 'Choco Pop Lollipop';
UPDATE products SET image_url = '/src/assets/products/golden-bite.jpg' WHERE name = 'Golden Bite';
UPDATE products SET image_url = '/src/assets/products/proti-bar.jpg' WHERE name = 'Proti Bar (Sugar Free)';